// Package internal provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package internal

import (
	"time"
)

// ConfigSpec Root configuration object
type ConfigSpec struct {
	// Devices Map of device name to connection specification.
	// Mapping key must be a valid label value
	Devices DevicesContainer `json:"devices" yaml:"devices"`
}

// DeviceConnectionSpec defines model for deviceConnectionSpec.
type DeviceConnectionSpec struct {
	// Address Device network address.
	// Might include port, but if not specified then 6668 is assumed.
	Address string `json:"address" yaml:"address"`

	// ConnectTimeout Connection timeout.
	// Default value is 10s
	ConnectTimeout time.Duration `json:"connectTimeout" yaml:"connectTimeout"`

	// Id Device ID from Tuya API
	Id string `json:"id" yaml:"id"`

	// Key Encryption key from Tuya API
	Key string `json:"key" yaml:"key"`

	// Protocol What protocol to use when talking to device.
	// Default value is "tuya3.1"
	Protocol string `json:"protocol" yaml:"protocol"`

	// ReadTimeout Network read timeout.
	// Default value is 10s
	ReadTimeout time.Duration `json:"readTimeout" yaml:"readTimeout"`

	// WriteTimeout Network write timeout.
	// Default value is 10s
	WriteTimeout time.Duration `json:"writeTimeout" yaml:"writeTimeout"`
}

// DevicesContainer Map of device name to connection specification.
// Mapping key must be a valid label value
type DevicesContainer map[string]DeviceConnectionSpec
