---
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=3m
          only-new-issues: true

      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
